apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-app
  template:
    metadata:
      labels:
        app: vuln-app
    spec:
      containers:
      - name: vuln-app
        image: devkukreja/vuln-app:v3
        ports:
        - containerPort: 5000
        # Optional: set resources to minimal for testing
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
        # No security hardening in this sample!
