apiVersion: v1
kind: Service
metadata:
  name: vuln-app-service
spec:
  selector:
    app: vuln-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Exposes externally for easy ingress
